package java.sql

/**
 * The object used for executing a static SQL statement and returning the results.
 */
trait Statement extends AutoCloseable {
  /**
   * Executes the given SQL statement, which returns a single ResultSet object.
   */
  def executeQuery(sql: String): ResultSet

  /**
   * Executes the given SQL statement, which may be an INSERT, UPDATE, or DELETE statement
   * or an SQL statement that returns nothing, such as an SQL DDL statement.
   */
  def executeUpdate(sql: String): Int

  /**
   * Executes the given SQL statement, which may return multiple results.
   */
  def execute(sql: String): Boolean

  /**
   * Retrieves the current result as a ResultSet object.
   */
  def getResultSet(): ResultSet

  /**
   * Retrieves the current result as an update count.
   */
  def getUpdateCount(): Int

  /**
   * Moves to this Statement object's next result.
   */
  def getMoreResults(): Boolean

  /**
   * Releases this Statement object's database and JDBC resources immediately.
   */
  def close(): Unit

  /**
   * Sets the maximum number of rows that any ResultSet object generated by this Statement
   * object can contain.
   */
  def setMaxRows(max: Int): Unit

  /**
   * Retrieves the maximum number of rows that a ResultSet object can contain.
   */
  def getMaxRows(): Int

  /**
   * Sets the number of seconds the driver will wait for a Statement object to execute.
   */
  def setQueryTimeout(seconds: Int): Unit

  /**
   * Retrieves the number of seconds the driver will wait for a Statement object to execute.
   */
  def getQueryTimeout(): Int

  /**
   * Cancels this Statement object if both the DBMS and driver support aborting an SQL statement.
   */
  def cancel(): Unit

  /**
   * Retrieves whether this Statement object has been closed.
   */
  def isClosed(): Boolean
}

object Statement {
  // Constants for getMoreResults
  final val CLOSE_CURRENT_RESULT = 1
  final val KEEP_CURRENT_RESULT = 2
  final val CLOSE_ALL_RESULTS = 3

  // Constants for result set types
  final val NO_GENERATED_KEYS = 1
  final val RETURN_GENERATED_KEYS = 2
} 